<?php

// error codes
const GENERAL_API_CODES_TRANSACTION_INITIATED = 1001;
const GENERAL_API_CODES_TRANSACTION_SUCCESSFUL = 1002;
const GENERAL_API_CODES_REQ_VALIDATION_FAILED = 1004;
const GENERAL_API_CODES_TRANSACTION_INITIATION_FAILED = 1005;
const GENERAL_API_CODES_TRANSACTION_EXECUTION_FAILED = 1007;
const GENERAL_API_CODES_TRANSACTION_NOT_FOUND = 1010;
const GENERAL_API_PAYMENT_PENDING = 1011;
const GENERAL_API_CODES_TRANSACTION_PENDING = 1006;

// status codes
