<?php

// error codes

const REQUEST_FAILED_VALIDATION_CODE = 100;
const ABILITY_SPECIFIED_NOT_FOUND_CODE = 101;
const MODEL_NOT_FOUND_CODE = 102;
const PHONE_NUMBER_ALREADY_VERIFIED_CODE = 103;
const INVALID_OTP_CODE = 104;
const INVALID_LOGIN_CREDENTIALS_CODE = 105;
const NO_IMAGE_FOUND_IN_REQUEST_CODE = 106;
const UNEXPLAINED_ERROR_CODE = 107;
const NO_NETWORK_FOUND_IN_MOMO_REQUEST_CODE = 108;
const MOMO_FUNDING_FAILED_CODE = 109;
const ONLY_CLIENTS_CAN_GENERATE_TOKEN_CODE = 110;
const INVALID_PIN_CODE = 111;
const NO_TRANSACTION_TOKEN_FOUND_IN_HEADER_CODE = 112;
const TRANSACTION_TOKEN_HAS_EXPIRED_CODE = 113;
const NO_USER_FOUND_FOR_THE_CONTACTS_PROVIDED_CODE = 114;
const INCOMPATIBLE_WALLET_CURRENCIES_CODE = 115;
const INSUFFICIENT_WALLET_BALANCE_CODE = 116;
const MULTIPLE_WALLET_OF_SAME_TYPE_NOT_SUPPORTED_CODE = 117;
const KYC_DETAIL_NOT_SET_CODE = 118;
const EMAIL_ALREADY_VERIFIED_CODE = 119;
const INVALID_USER_EMAIL_FOR_PASSWORD_RESET_CODE = 120;
const USER_NOT_SUBSCRIBED_TO_FIREBASE_CODE = 121;
const OTP_HAS_EXPIRED_CODE = 122;
const SAME_USER_PAYMENT_REQUEST_IS_UNSUPPORTED_CODE = 123;
const WALLET_TYPE_IS_NOT_SUPPORTED_IN_COUNTRY_CODE = 124;
const PAYMENT_METHOD_NOT_SUPPORTED_BY_WALLET_EXCEPTION_CODE = 125;
const VISA_TRANSACTION_FAILED_VALIDATION_CODE = 126;
const UNSUCCESSFUL_CASHOUT_TOTELLER_CODE = 127;
const UNSUCCESSFUL_CASHOUT_TOFLUTTERWAVE_CODE = 128;
const NG_BANK_USSD_CASHIN_FAILED_CODE_FAILED = 129;
const BILLING_AND_WALLET_CURRENCY_MISMATCH_CODE = 131;
const BILLING_FEE_AND_AMOUNT_PAID_MISMATCH_CODE = 132;
const UNSUCCESSFUL_BILL_PAYMENT_TO_FLUTTERWAVE_CODE = 133;
const TELLER_VBV_VERIFICATION_FAILED_CODE = 134;
const PAYMENT_REQUEST_EXPIRED_CODE = 135;
const PAYMENT_REQUEST_NOT_OWNED_BY_USER_CODE = 136;
const PAYMENT_REQUEST_ALREADY_COMPLETED_CODE = 137;
const USER_ALREADY_HAS_A_PERSONAL_ACCOUNT_CODE = 138;
const USER_ALREADY_HAS_A_MERCHANT_ACCOUNT_CODE = 139;
const ACTION_IS_FORBIDDEN_CODE = 140;
const SENDING_PAYMENT_TO_SELF_UNSUPPORTED_CODE = 141;
const ACCOUNT_RESOLUTION_FAILED_CODE = 142;
const PAYMENT_EXPIRED_CODE = 143;
const INVALID_BEARER_TOKEN_CODE = 144;
const USER_DOES_NOT_HAVE_A_WALLET_IN_REQUESTED_CURRENCY_CODE = 145;
const INVALID_TRANSACTION_AMOUNT_CODE = 146;
const RECEIPIENT_EXISTS_CODE = 147;
const SELF_CANNOT_BE_A_RECEIPIENT_CODE = 148;
const PAYMENT_METHOD_EXISTS_FOR_CLIENT_CODE = 149;
const INSUFFICIENT_PROVIDER_BALANCE_CODE = 666;

const NG_BANK_TRANSFER_CASHIN_FAILED_CODE_FAILED = 170;
const MTN_VOUCHER_CASHOUT_FAILED_CODE_FAILED = 190;
const GIFT_PESA_VOUCHER_FAILED_CODE = 192;
const KCB_CASHOUT_FAILED_CODE = 193;
const CHAKA_MINI_APP_FAILED_CODE = 195;
const SOMETHING_WENT_WRONG_CODE = 196;

const NO_MERCHANT_FOUND_WITH_THE_SEARCH_DATA_PROVIDED = 152;
const USER_IS_NOT_AUTHORIZED_TO_ACCESS_ROUTE_CODE = 153;
const QUERY_PARAM_NOT_FOUND_IN_URL_CODE = 154;
const PRODUCT_AND_DESCRIPTION_MISMATCH_CODE = 155;
const MERCHANT_DOES_NOT_OWN_PRODUCT_CODE = 156;
const ITEM_OUT_OF_STOCK_CODE = 157;
const STOCK_QTY_LESS_THAN_REQUESTED_QTY_CODE = 158;
const CUSTOMER_ALREADY_EXISTS_CODE = 159;
const BAD_REQUEST_CODE = 163;
const TIMEOUT_CODE = 164;
const TOO_MANY_ATTEMPT = 429;

const UNSUCCESSFUL_CASHOUT_TOUBACODE = 400;
const UNSUCCESSFUL_CASHOUT_TOWEMACODE = 401;
const UNSUPPORTED_PAYMENT_METHOD_BY_PROVIDER_CODE = 150;
const MPESA_FLUTTERWAVE_CASHIN_FAILED_CODE_FAILED = 151;
const THETELLER_MOMO_TRANSACTION_DECLINED_CODE = 166;
const THETELLER_INSUFFICIENT_MOMO_BALANCE_CODE = 167;
const THETELLER_ACCESS_DENIED_CODE = 168;
const THETELLER_CARDHOLDER_NOT_PERMITTED_CODE = 169;
const THETELLER_DUPLICATE_TRANSACTION_ID_CODE = 170;
const THETELLER_INVALID_AMOUNT_OR_TRANSACTION_ID_CODE = 171;
const THETELLER_INVALID_CREDENTIAL_CODE = 172;
const THETELLER_INVALID_VOUCHER_CODE = 173;
const THETELLER_MERCHANT_ID_NOT_SET_CODE = 174;
const THETELLER_SUBSCRIBER_IS_NOT_MOMO_REGISTERED_CODE = 175;
const THETELLER_TRANSACTION_FAILED_OR_DECLINED_CODE = 176;
const THETELLER_USSD_IS_BUSY_CODE = 177;
const THETELLER_VBV_REQUIRED_CODE = 178;
const THETELLER_WRONG_PIN_OR_TIMEOUT_CODE = 179;
const INVALID_MPESA_FUNDING_REQUEST_CODE = 180;
const CELLULANT_TRANSACTION_FAILED_CODE = 181;
const CELLULANT_TRANSACTION_SUCCESSFUL_CODE = 188;

const UNSUCCESSFUL_AIRTIME_PURCHASE_CODE = 181;

// OTP err codes
const OTP_VERIFICATION_FAILED_CODE = 182;

// Paywithbrij err codes
const BRIJ_WALLET_PAYMENT_FAILED_CODE = 183;

const UNAUTHORIZED_ACTION_CODE = 184;

const PRODUCT_PAYMENT_FAILED_CODE = 185;

const MERCHANT_PAYMENT_FAILED_CODE = 186;

const GH_BANK_CASHOUT_FAILED_CODE = 187;
const BRIJ_DELAY_IN_REQUEST = 60;
const UNREGISTERED_PROCESSOR_CODE = 161;

const UNSUCCESSFUL_CASHOUT_TOCELLULANT_CODE = 190;
const PENDING_CASHOUT_TOCELLULANT_CODE = 191;

const UNSUCCESSFUL_CASHOUT_TO_TEMBOPLUS_CODE = 192;
const PENDING_CASHOUT_TO_TEMBOPLUS_CODE = 193;
const SUCCESSFUL_CASHOUT_TO_TEMBOPLUS_CODE = 194;
const PENDING_CASHOUT_TO_PAYSTACK_CODE = 196;
const SUCCESSFUL_CASHOUT_TO_PAYSTACK_CODE = 197;
const UNSUCCESSFUL_CASHOUT_TO_PAYSTACK_CODE = 198;

const UNSUCCESSFUL_CASHOUT_TO_DCM_CODE = 200;
const PENDING_CASHOUT_TO_DCM_CODE = 201;
const SUCCESSFUL_CASHOUT_TO_DCM_CODE = 202;

// cellulant account validation
const CELLULANT_ACCOUNT_VALIDATION_SERVICE_NOT_AVAILABLE = 167;
const CELLULANT_ACCOUNT_VALIDATION_FEATURE_UNSUBSCRIBED = 301;
const CELLULANT_ACCOUNT_NUMBER_NOT_FOUND = 306;
const CELLULANT_ACCOUNT_IS_VALID = 307;
const CELLULANT_INVALID_CREDS = 132;
