<?php

// error codes

const REQUEST_FAILED_VALIDATION_CODE = 100;
const ABILITY_SPECIFIED_NOT_FOUND_CODE = 101;
const MODEL_NOT_FOUND_CODE = 102;
const PHONE_NUMBER_ALREADY_VERIFIED_CODE = 103;
const INVALID_OTP_CODE = 104;
const INVALID_LOGIN_CREDENTIALS_CODE = 105;
const NO_IMAGE_FOUND_IN_REQUEST_CODE = 106;
const UNEXPLAINED_ERROR_CODE = 107;
const NO_NETWORK_FOUND_IN_MOMO_REQUEST_CODE = 108;
const MOMO_FUNDING_FAILED_CODE = 109;
const ONLY_CLIENTS_CAN_GENERATE_TOKEN_CODE = 110;
const INVALID_PIN_CODE = 111;
const NO_TRANSACTION_TOKEN_FOUND_IN_HEADER_CODE = 112;
const TRANSACTION_TOKEN_HAS_EXPIRED_CODE = 113;
const NO_USER_FOUND_FOR_THE_CONTACTS_PROVIDED_CODE = 114;
const INCOMPATIBLE_WALLET_CURRENCIES_CODE = 115;
const INSUFFICIENT_WALLET_BALANCE_CODE = 116;
const MULTIPLE_WALLET_OF_SAME_TYPE_NOT_SUPPORTED_CODE = 117;
const KYC_DETAIL_NOT_SET_CODE = 118;
const EMAIL_ALREADY_VERIFIED_CODE = 119;
const INVALID_USER_EMAIL_FOR_PASSWORD_RESET_CODE = 120;
const USER_NOT_SUBSCRIBED_TO_FIREBASE_CODE = 121;
const OTP_HAS_EXPIRED_CODE = 122;
const SAME_USER_PAYMENT_REQUEST_IS_UNSUPPORTED_CODE = 123;
const WALLET_TYPE_IS_NOT_SUPPORTED_IN_COUNTRY_CODE = 124;
const PAYMENT_METHOD_NOT_SUPPORTED_BY_WALLET_EXCEPTION_CODE = 125;
const VISA_TRANSACTION_FAILED_VALIDATION_CODE = 126;
const UNSUCCESSFUL_CASHOUT_TOTELLER_CODE = 127;
const UNSUCCESSFUL_CASHOUT_TOFLUTTERWAVE_CODE = 128;
const NG_BANK_USSD_CASHIN_FAILED_CODE_FAILED = 129;
const BILLING_AND_WALLET_CURRENCY_MISMATCH_CODE = 131;
const BILLING_FEE_AND_AMOUNT_PAID_MISMATCH_CODE = 132;
const UNSUCCESSFUL_BILL_PAYMENT_TO_FLUTTERWAVE_CODE = 133;
const TELLER_VBV_VERIFICATION_FAILED_CODE = 134;
const PAYMENT_REQUEST_EXPIRED_CODE = 135;
const PAYMENT_REQUEST_NOT_OWNED_BY_USER_CODE = 136;
const PAYMENT_REQUEST_ALREADY_COMPLETED_CODE = 137;
const USER_ALREADY_HAS_A_PERSONAL_ACCOUNT_CODE = 138;
const USER_ALREADY_HAS_A_MERCHANT_ACCOUNT_CODE = 139;
const ACTION_IS_FORBIDDEN_CODE = 140;
const SENDING_PAYMENT_TO_SELF_UNSUPPORTED_CODE = 141;
const ACCOUNT_RESOLUTION_FAILED_CODE = 142;
const PAYMENT_EXPIRED_CODE = 143;
const INVALID_BEARER_TOKEN_CODE = 144;
const USER_DOES_NOT_HAVE_A_WALLET_IN_REQUESTED_CURRENCY_CODE = 145;
const INVALID_TRANSACTION_AMOUNT_CODE = 146;
const RECEIPIENT_EXISTS_CODE = 147;
const SELF_CANNOT_BE_A_RECEIPIENT_CODE = 148;
const PAYMENT_METHOD_EXISTS_FOR_CLIENT_CODE = 149;
const INSUFFICIENT_PROVIDER_BALANCE_CODE = 666;

const NG_BANK_TRANSFER_CASHIN_FAILED_CODE_FAILED = 170;
const MTN_VOUCHER_CASHOUT_FAILED_CODE_FAILED = 190;
const GIFT_PESA_VOUCHER_FAILED_CODE = 192;
const KCB_CASHOUT_FAILED_CODE = 193;
const CHAKA_MINI_APP_FAILED_CODE = 195;
const SOMETHING_WENT_WRONG_CODE = 196;

const NO_MERCHANT_FOUND_WITH_THE_SEARCH_DATA_PROVIDED = 152;
const USER_IS_NOT_AUTHORIZED_TO_ACCESS_ROUTE_CODE = 153;
const QUERY_PARAM_NOT_FOUND_IN_URL_CODE = 154;
const PRODUCT_AND_DESCRIPTION_MISMATCH_CODE = 155;
const MERCHANT_DOES_NOT_OWN_PRODUCT_CODE = 156;
const ITEM_OUT_OF_STOCK_CODE = 157;
const STOCK_QTY_LESS_THAN_REQUESTED_QTY_CODE = 158;
const CUSTOMER_ALREADY_EXISTS_CODE = 159;
const BAD_REQUEST_CODE = 163;
const TIMEOUT_CODE = 164;
const TOO_MANY_ATTEMPT = 429;

const UNSUCCESSFUL_CASHOUT_TOUBACODE = 400;
const UNSUCCESSFUL_CASHOUT_TOWEMACODE = 401;
const UNSUPPORTED_PAYMENT_METHOD_BY_PROVIDER_CODE = 150;
const MPESA_FLUTTERWAVE_CASHIN_FAILED_CODE_FAILED = 151;
const THETELLER_MOMO_TRANSACTION_DECLINED_CODE = 166;
const THETELLER_INSUFFICIENT_MOMO_BALANCE_CODE = 167;
const THETELLER_ACCESS_DENIED_CODE = 168;
const THETELLER_CARDHOLDER_NOT_PERMITTED_CODE = 169;
const THETELLER_DUPLICATE_TRANSACTION_ID_CODE = 170;
const THETELLER_INVALID_AMOUNT_OR_TRANSACTION_ID_CODE = 171;
const THETELLER_INVALID_CREDENTIAL_CODE = 172;
const THETELLER_INVALID_VOUCHER_CODE = 173;
const THETELLER_MERCHANT_ID_NOT_SET_CODE = 174;
const THETELLER_SUBSCRIBER_IS_NOT_MOMO_REGISTERED_CODE = 175;
const THETELLER_TRANSACTION_FAILED_OR_DECLINED_CODE = 176;
const THETELLER_USSD_IS_BUSY_CODE = 177;
const THETELLER_VBV_REQUIRED_CODE = 178;
const THETELLER_WRONG_PIN_OR_TIMEOUT_CODE = 179;
const INVALID_MPESA_FUNDING_REQUEST_CODE = 180;
const CELLULANT_TRANSACTION_FAILED_CODE = 181;
const CELLULANT_TRANSACTION_SUCCESSFUL_CODE = 188;

const UNSUCCESSFUL_AIRTIME_PURCHASE_CODE = 181;

// OTP err codes
const OTP_VERIFICATION_FAILED_CODE = 182;

// Paywithbrij err codes
const BRIJ_WALLET_PAYMENT_FAILED_CODE = 183;

const UNAUTHORIZED_ACTION_CODE = 184;

const PRODUCT_PAYMENT_FAILED_CODE = 185;

const MERCHANT_PAYMENT_FAILED_CODE = 186;

const GH_BANK_CASHOUT_FAILED_CODE = 187;
const BRIJ_DELAY_IN_REQUEST = 60;
const UNREGISTERED_PROCESSOR_CODE = 161;

const UNSUCCESSFUL_CASHOUT_TOCELLULANT_CODE = 190;
const PENDING_CASHOUT_TOCELLULANT_CODE = 191;

const UNSUCCESSFUL_CASHOUT_TO_TEMBOPLUS_CODE = 192;
const PENDING_CASHOUT_TO_TEMBOPLUS_CODE = 193;
const SUCCESSFUL_CASHOUT_TO_TEMBOPLUS_CODE = 194;
const PENDING_CASHOUT_TO_PAYSTACK_CODE = 196;
const SUCCESSFUL_CASHOUT_TO_PAYSTACK_CODE = 197;
const UNSUCCESSFUL_CASHOUT_TO_PAYSTACK_CODE = 198;

const UNSUCCESSFUL_CASHOUT_TO_DCM_CODE = 200;
const PENDING_CASHOUT_TO_DCM_CODE = 201;
const SUCCESSFUL_CASHOUT_TO_DCM_CODE = 202;

// cellulant account validation
const CELLULANT_ACCOUNT_VALIDATION_SERVICE_NOT_AVAILABLE = 167;
const CELLULANT_ACCOUNT_VALIDATION_FEATURE_UNSUBSCRIBED = 301;
const CELLULANT_ACCOUNT_NUMBER_NOT_FOUND = 306;
const CELLULANT_ACCOUNT_IS_VALID = 307;
const CELLULANT_INVALID_CREDS = 132;

// const ;

// non-error codes
const SENT_PAYMENT_EXPIRY_TIME = 259200;
const OTP_EXPIRES_IN = 6000;
const PAYMENT_ACCEPTANCE_EXPIRES_IN = 259200;
const USER_INVITATION_EXPIRES_IN = 259200;
const FCM_TEST_TOKEN = 'fFEYhKTfN010rDvHICqvlF:APA91bHFW2RfrVakOratXy-NEuiqXP9eCyTsNa_hx8aDv0G37DXAMjDfQAUKNJdoo_Bhe5WbrKT_g1Af1OX38_xMF5oJvvwfd_-JJGVosu9Du7QyRue8O437EOK5o3bo2IuhrWuWoz5h';
const FLUTTERWAVE_BASE_URL = 'https://api.flutterwave.com/v3';
const WAVE_SECRET_KEY = 'FLWSECK_TEST-bc75f5230b2f3e436dd2fc99c844d933-X';
const WAVE_ENCRYPTION_KEY = 'FLWSECK_TEST32670f0923ae';
const UBA_BASE_URL = 'https://gateway.ubaopenbanking.com/remittanceplatform';
const UBA_PROD_BASE_URL = 'https://gateway.ubaopenbanking.com/prod/remittanceplatform';
const PROXY_URL = '172.24.16.112/api/v1/receive/payload';
const WEMA_BASE_URL = 'https://172.27.5.41/MerchantsAPIService/api';
const WEMA_DEV_URL = 'https://apps.wemabank.com/WemaAPIService/api';
const DEV_USR = 'centrikgateway';
const DEV_PASS = 'test12345';
const PWB_OTP_ENABLED = 1;
const WEMA_ENABLED = 1;

// IDs
const THETELLER_MERCHANT_ID = 'TTM-00005860';
const THETELLER_PASSCODE = '1c74ae5782126dcd0763f59598e74770';

// success codes
const TELLER_VISA_TRANSACTION_COMPLETED_CODE = 700;
const WAVE_VISA_TRANSACTION_COMPLETED_CODE = 701;

// kyc email verificatin
const KYC_ID_VERIFICATION_FAILED_CODE = 721;
const USER_UPDATE_FAILED_CODE = 722;

// Wema Codes
const WEMA_BANK_CODE = '000017';
const WEMA_LOOKUP_SUCCESS = '00';
const WEMA_LOOKUP_FAIL = '07';

// PayWithBrij Codes
const PWB_SUCCESSFUL_CODE = '00';
const PWB_FAILED_CODE = '01';
const PWB_NO_CALLBACK_CODE = '02';
const PWB_BEING_PROCESSED_CODE = '03';
const PWB_FAILED_VALIDATION = '04';
const PWB_TIMED_OUT = '05';
const PWB_METHOD_UNAVAILABLE = '06';
const PWB_OTP_EXPIRES_IN = '180';
const PWB_TELLER_REQ_TIMEOUT = 5;
const PWB_INSUFFICIENT_FUNDS = '06';
// const PWB_OTP_EXPIRES_IN='600';
const PWB_OTP_MESSAGE = '%s sent you a payment request from :brij. Kindly confirm with OTP %d on their app. OTP is valid for %s';

// UBA Codes
const UBA_SUCCESS = '00';
const UBA_FAIL = '07';

// brijx codes
const BRIJX_OFFER_CREATION_SUCCESS = 800;
const BRIJX_OFFER_CREATION_FAILED = 801;
const BRIJX_OFFERS_SUCCESS = 803;
const BRIJX_OFFERS_UNAVAILABLE = 804;
const BRIJX_SWAP_SUCCESS = 805;
const BRIJX_SWAP_FAILED = 806;
const BRIJX_OFFER_UPDATE_SUCCESS = 807;
const BRIJX_OFFER_UPDATE_FAILED = 808;
const BRIJX_ADVISORY_RATE = 809;
const BRIJX_OFFERS_TOP_EXCHANGES = 810;
const OFFER_NO_LONGER_AVAILABLE = 812;
const BRIJX_RATE_TOO_LOW_OR_HIGH = 813;
const BRIJX_OFFER_TRANSACTIONS = 815;
const BRIJX_OFFER_DELETE_SUCCESS = 816;

// merchants
const MERCHANT_PORTAL_URL = 'https://pay.brij.live';
// kcbtill
const TILL_NOT_FOUND_CODE = '796';
// wallet abilities
const CAN_CASH_OUT = 'can-cashout';
const CAN_CASH_IN = 'can-cashin';
const CAN_SEND = 'can-send';
const CAN_REQUEST = 'can-request';
const CAN_SWAP = 'can-swap';
const CAN_PAY_MERCHANT = 'can-pay-merchant';
const CAN_BRIJX = 'can-brijx';
const CAN_USE_PAY_WITH_BRIJ = 'can-use-pwb';
const CAN_USE_MERCHANT_PAYMENT_LINK = 'can-use-merchant-payment-link';
const CAN_PAY_WITH_BRIJ = 'can-pay-with-brij';
// const CAN_AUTO_DEBIT = 'can-auto-debit';

// Braas Codes
const BRAAS_TRANSACTION_INITIATED = '1000';
const BRAAS_INITIATE_SUCCESSFUL = '1001';
const BRAAS_TRANSACTION_SUCCESSFUL = '1002';
const BRAAS_FAILED_VALIDATION = '1004';
const BRAAS_INITIATE_FAILED = '1005';
const BRAAS_TRANSACTION_COMPLETE = '1003';
const BRAAS_TRANSACTION_PENDING = '1006';
const BRAAS_TRANSACTION_FAILED = '1007';
const BRAAS_METHOD_UNAVAILABLE = '1008';
const BRAAS_ACCOUNT_RESOLUTION_FAILED = '1009';
const BRAAS_TRANSACTION_UNAVAILABLE = '1010';
const BRAAS_DUPLICATE_ID = '1011';
const BRAAS_INSUFFICIENT_BALANCE = '1014';
const BRAAS_PAYER_LIMIT_REACHED = '1015';
const BRAAS_ACCOUNT_RESOLUTION_SUCCESS = '1016';
const BRAAS_ERRMSG_CONTACT_SUPPORT = 'An error occured. Please contact support';
const BRAAS_INVALID_MPESA_AMOUNT_ERR_CODE = '1017';
const BRAAS_AMOUNT_NOT_ALLOWED = '1018';
const MERCHANT_ACTIVE_CODE = 6;

// DCM
const DCM_MTN_GHANA_BANK_CODE = '300591';
const DCM_AIRTEL_TIGO_GHANA_BANK_CODE = '300592';
const DCM_VODAFONE_GHANA_BANK_CODE = '300594';

const TOKEN_EXPIRATION_IN_HOURS = 5;

const LOGIN_LOCK_ACTION_EXPIRE_IN_SECONDS = 60;
const USSD_LOCK_ACTION_EXPIRE_IN_MINUTES = 20; // 1200 sec

// PAYOUT STATUS CODES
const SUCCESSFUL_PAYOUT_STATUS_CODE = '000';
const PENDING_PAYOUT_STATUS_CODE = '001';
const TIMEOUT_PAYOUT_STATUS_CODE = '003';
const FAILED_PAYOUT_STATUS_CODE = '002';

const HTTP_TIMED_OUT_STATUS_CODE = 408;
const HTTP_UNPROCESSED_STATUS_ENTITY_CODE = 422;
const HTTP_SUCCESSFUL_STATUS_CODE = 200;

// BPAAS STATUS CODES
const BPAAS_TRANSACTION_SUCCESSFUL_STATUS_CODE = '1002';
const BPAAS_TRANSACTION_PENDING_STATUS_CODE = '1006';
const BPAAS_TRANSACTION_TIMEOUT_STATUS_CODE = '9999';
const BPAAS_TRANSACTION_FAILED_STATUS_CODE = '1007';
const BPAAS_INSUFFICIENT_WALLET_BALANCE_STATUS_CODE = '1014';
const BPAAS_METHOD_UNAVAILABLE = '1008';
